---
- hosts: stackstorm
  become: true
  roles:
    - mongodb
    - rabbitmq
    - st2repos
    - postgresql
    - st2mistral
    - st2
    - st2web
    - st2smoketests
    - st2pack
    - st2-fetch-key
