- name: restart st2
  become: true
  command: "{{ item }}"
  with_items:
      #- st2ctl reload --register-all
    - st2ctl reload --register-actions
    - st2ctl restart

- name: restart st2api/st2stream
  become: true
  command: "st2ctl restart-component {{ item }}"
  with_items:
    - st2api
    - st2stream
